const fs = require('fs');

const languages = {
  en: {
    Index: {
      category: "Global Technology & AI Intelligence",
      title1: "The Future of Technology",
      title2: "Is Written While You Sleep.",
      subtitle: "Beyond the mainstream media. Discover the next-generation AI tools, corporate breakthroughs, and digital innovations shaping tomorrow's ecosystem.",
      cta: "Explore Insights",
      ctaLatest: "Latest Analysis",
      ctaExplore: "Explore Reports",
      secFeatured: "Featured",
      secLatest: "Latest Intelligence",
      viewArchive: "View Archive",
      readMore: "Read More",
      statReports: "Intel Reports",
      statNations: "Nations Tracked",
      statSubscribers: "Subscribers"
    },
    Header: {
      breaking: "BREAKING",
      ticker: [
        "NEW ERA IN AI REGULATIONS BEGINS",
        "UNEXPECTED BREAKTHROUGH IN QUANTUM CHIP PRODUCTION",
        "JOINT STATEMENT FROM GLOBAL TECH GIANTS",
        "NEXT-GEN AUTONOMOUS VEHICLES HIT CITY STREETS",
        "SENTIENT WIRE EXCLUSIVE: ARCHITECTS OF THE FUTURE"
      ],
      nav: {
        home: "HOME",
        cybersecurity: "CYBERSECURITY",
        ai: "AI",
        hardware: "HARDWARE"
      },
      login: "Account Login"
    },
    Footer: {
      description: "Uncovering the technologies, defense contracts, and corporate strategies that shape the future before they reach the mainstream.",
      categories: "Categories",
      cybersecurity: "Cybersecurity",
      ai: "AI",
      quantum: "Quantum",
      hardware: "Hardware",
      defense: "Defense",
      corporate: "Corporate",
      about: "About Us",
      careers: "Careers",
      contact: "Contact",
      legal: "Legal",
      privacy: "Privacy Policy",
      terms: "Terms of Service",
      cookies: "Cookie Policy",
      allRightsReserved: "All rights reserved.",
      systemActive: "SYSTEM ACTIVE"
    },
    News: {
      decrypting: "DECRYPTING DATABANK...",
      notFound: "404 - INTEL NOT FOUND",
      returnToBase: "RETURN TO BASE",
      decrypted: "DECRYPTED",
      satelliteImagery: "SATELLITE IMAGERY: SECURED",
      terminalTitle: "terminal.exe",
      awaitingTelemetry: "Awaiting further telemetry",
      shareIntel: "SHARE INTEL",
      reportId: "REPORT ID",
      t1: "> INITIALIZING THREAT ANALYSIS...",
      t2: "> DECRYPTING PAYLOAD SIGNATURE [0x9F42C]...",
      t3: "[CRITICAL] ZERO-DAY DETECTED IN SCADA PROTOCOL",
      t4: "> MAPPING THREAT ORIGIN: UNKNOWN_NODE_492",
      t5: "> ESTABLISHING SECURE HANDSHAKE...",
      success: "[SUCCESS]",
      timeout: "[TIMEOUT]",
      escalationTitle: "The Escalation of Cyber-Kinetic Warfare",
      escalationP1: "Unlike previous attacks which focused primarily on data exfiltration and corporate espionage, this latest vector demonstrates a clear intent to cause physical, kinetic damage. By manipulating the frequency controls of the targeted substations, the attackers attempted to induce hardware failures that could have resulted in localized blackouts lasting weeks.",
      escalationP2: "Global intelligence agencies are currently working in tandem with the private sector to patch the vulnerabilities and trace the origin of the attack. Until a comprehensive patch is deployed, grid operators remain on high alert. We will continue to monitor the situation as it develops and provide updates on the live ticker."
    },
    About: {
      title: "About Us",
      name: "Sentient Wire",
      subtitle: "Where our name comes from",
      history1: "In the 19th century, when the first telegraph lines were laid across continents, humanity was shaken by the miracle of communication at an unprecedented speed. Thinkers of the time called these intercontinental cables 'The Sentient Wire', seeing them as a living nervous system for the world.",
      history2: "Today, in a world wrapped in AI, quantum computers, and IoT, this metaphor has become a reality.",
      missionTitle: "Our Mission",
      missionP1: "We are an independent journalism network dedicated to understanding and explaining how AI and deep technologies are shaping the world.",
      missionP2: "Our task is not just to introduce new software. We discover what's being discussed behind closed doors in Silicon Valley and the hidden effects of algorithms before they reach mainstream media.",
      visionTitle: "Journalism Vision",
      visionP1: "We adopt a journalism approach that is evidence-based but boundary-pushing. We treat technology not just as a tool, but as the next evolution of humanity.",
      manifesto: "The future is written by those who understand it. We are the ones who read the truth within this massive and conscious network surrounding the world."
    },
    Privacy: {
      title: "Privacy Policy",
      lastUpdate: "LAST UPDATE",
      s1Title: "1. Data Collection and Processing",
      s1P1: "We prioritize the privacy of our users. Protecting the anonymity and digital security of our readers is our fundamental principle. We only collect the minimum necessary data (server logs, IP address, basic browser info) for the operation of our platform.",
      s2Title: "2. Purpose of Data Use",
      s2P1: "Collected data is only used for:",
      s2Item1: "Detecting cyber attacks, bot traffic, and unusual movements.",
      s2Item2: "Optimizing platform performance and reading experience.",
      s2Item3: "Safely maintaining data within legal obligations (without sharing with third parties except by court order).",
      s3Title: "3. Sharing with Third Parties",
      s3P1: "We NEVER sell or share your user data with advertising networks, data brokers, or third-party analysis companies. Our system operates on a completely closed-circuit infrastructure."
    }
  },
  tr: {
    Index: {
      category: "Küresel Teknoloji & Yapay Zeka Gündemi",
      title1: "Teknolojinin Geleceği",
      title2: "Siz Uyurken Yazılıyor.",
      subtitle: "Ana akım medyanın ötesine geçin. Geleceğin ekosistemini şekillendiren yeni nesil yapay zeka araçlarını, kurumsal atılımları ve dijital inovasyonları keşfedin.",
      cta: "Özel Haberleri İncele",
      ctaLatest: "Özel Haberleri İncele",
      ctaExplore: "Raporları Keşfet",
      secFeatured: "Öne Çıkanlar",
      secLatest: "Son İstihbarat",
      viewArchive: "Arşivi Görüntüle",
      readMore: "Devamını Oku",
      statReports: "İstihbarat Raporu",
      statNations: "İzlenen Ülke",
      statSubscribers: "Abone"
    },
    Header: {
      breaking: "SON DAKİKA",
      ticker: [
        "YAPAY ZEKA DÜZENLEMELERİNDE YENİ DÖNEM BAŞLIYOR",
        "KUANTUM ÇİP ÜRETİMİNDE BEKLENMEYEN ATILIM",
        "GLOBAL TEKNOLOJİ DEVLERİNDEN ORTAK BİLDİRİ",
        "YENİ NESİL OTONOM ARAÇLAR ŞEHİR TESTİNE ÇIKTI",
        "SENTIENT WIRE ÖZEL RÖPORTAJ: GELECEĞİN MİMARLARI"
      ],
      nav: {
        home: "ANA SAYFA",
        cybersecurity: "SİBER GÜVENLİK",
        ai: "YAPAY ZEKA",
        hardware: "DONANIM"
      },
      login: "Hesap Girişi"
    },
    Footer: {
      description: "Yapay zeka devrimini, gelecek teknolojilerini ve dijital dünyadaki kırılma noktalarını herkesten önce keşfedin.",
      categories: "Kategoriler",
      cybersecurity: "Siber Güvenlik",
      ai: "Yapay Zeka",
      quantum: "Kuantum",
      hardware: "Donanım",
      defense: "Savunma",
      corporate: "Kurumsal",
      about: "Hakkımızda",
      careers: "Kariyer",
      contact: "İletişim",
      legal: "Yasal",
      privacy: "Gizlilik Politikası",
      terms: "Kullanım Koşulları",
      cookies: "Çerez Politikası",
      allRightsReserved: "Tüm hakları saklıdır.",
      systemActive: "SİSTEM AKTİF"
    },
    News: {
      decrypting: "VERİ TABANI DEŞİFRE EDİLİYOR...",
      notFound: "404 - İSTİHBARAT BULUNAMADI",
      returnToBase: "ÜSSE GERİ DÖN",
      decrypted: "DEŞİFRE EDİLME",
      satelliteImagery: "UYDU GÖRÜNTÜSÜ: GÜVENLİ",
      terminalTitle: "terminal.exe",
      awaitingTelemetry: "Yeni telemetri verileri bekleniyor",
      shareIntel: "İSTİHBARATI PAYLAŞ",
      reportId: "RAPOR KODU",
      t1: "> TEHDİT ANALİZİ BAŞLATILIYOR...",
      t2: "> VERİ BLOK İMZASI DEŞİFRE EDİLİYOR [0x9F42C]...",
      t3: "[KRİTİK] SCADA PROTOKOLÜNDE SIFIR-GÜN ZAFİYETİ TESPİT EDİLDİ",
      t4: "> TEHDİT KAYNAĞI HARİTALANIYOR: UNKNOWN_NODE_492",
      t5: "> GÜVENLİ BAĞLANTI KURULUYOR...",
      success: "[BAŞARILI]",
      timeout: "[ZAMAN AŞIMI]",
      escalationTitle: "Siber-Kinetik Savaşın Tırmanışı",
      escalationP1: "Veri sızıntısı ve kurumsal casusluğa odaklanan önceki saldırıların aksine, bu son saldırı vektörü fiziksel ve kinetik hasar verme niyetini açıkça ortaya koymaktadır. Saldırganlar hedef alınan alt istasyonların frekans kontrollerini manipüle ederek, haftalarca sürebilecek bölgesel elektrik kesintilerine yol açabilecek donanım arızalarını tetiklemeye çalıştılar.",
      escalationP2: "Küresel istihbarat kurumları, güvenlik açıklarını yamamak ve saldırının kaynağını izlemek için şu anda özel sektörle iş birliği içinde çalışmaktadır. Kapsamlı bir yama dağıtılana kadar şebeke operatörleri yüksek alarm durumunda kalmaya devam edecektir. Durumu yakından takip etmeye ve canlı akış üzerinden güncellemeler sunmaya devam edeceğiz."
    },
    About: {
      title: "Hakkımızda",
      name: "Sentient Wire",
      subtitle: "İsmimiz Nereden Geliyor?",
      history1: "19. yüzyılda kıtaları birbirine bağlayan ilk telgraf hatları çekildiğinde, insanlık o güne dek görülmemiş bir hızda iletişim kurmanın mucizesiyle sarsıldı. Dönemin düşünürleri bu kıtalararası kablolara 'The Sentient Wire' (Hissedebilen / Bilinçli Kablo) adını taktılar.",
      history2: "Bugün, yapay zeka, kuantum bilgisayarlar ve nesnelerin interneti ile sarılı olan dünyamızda, bu 'bilinçli ağ' metaforu artık bir gerçekliğe dönüştü.",
      missionTitle: "Misyonumuz",
      missionP1: "Sentient Wire olarak biz, yapay zeka ve derin teknolojilerin dünyayı nasıl şekillendirdiğini anlamaya ve anlatmaya adanmış bağımsız bir gazetecilik ağıyız.",
      missionP2: "Bizim görevimiz sadece yeni çıkan bir yazılımı tanıtmak değildir. Biz; silikon vadisindeki kapalı kapılar ardında konuşulanları ve algoritmaların gizli etkilerini ana akım medyaya düşmeden önce keşfediyoruz.",
      visionTitle: "Gazetecilik Vizyonumuz",
      visionP1: "Kanıta ve veriye dayalı, ancak bir o kadar da sınırları zorlayan bir gazetecilik anlayışı benimsiyoruz. Teknolojiyi sadece bir araç olarak değil, insanlığın bir sonraki evrimi olarak ele alıyoruz.",
      manifesto: "Gelecek, onu anlayanlar tarafından yazılır. Biz, dünyayı saran bu devasa ve bilinçli ağın içindeki gerçeği okuyanlarız."
    },
    Privacy: {
      title: "Gizlilik Politikası",
      lastUpdate: "SON GÜNCELLEME",
      s1Title: "1. Veri Toplama ve İşleme",
      s1P1: "Kullanıcılarımızın gizliliğine en üst düzeyde önem veriyoruz. Okurlarımızın anonimliğini ve dijital güvenliğini korumak temel prensibimizdir. Yalnızca platformun işleyişi için zorunlu olan minimum verileri topluyoruz.",
      s2Title: "2. Verilerin Kullanım Amacı",
      s2P1: "Toplanan veriler yalnızca şu amaçlar için kullanılır:",
      s2Item1: "Siber saldırıları ve olağandışı hareketleri tespit etmek.",
      s2Item2: "Platformun performansını ve okuma deneyimini optimize etmek.",
      s2Item3: "Yasal zorunluluklar kapsamında verileri güvenli şekilde muhafaza etmek.",
      s3Title: "3. Üçüncü Taraflarla Paylaşım",
      s3P1: "Kullanıcı verilerinizi ASLA reklam ağlarına veya üçüncü taraf şirketlere satmıyoruz. Sistemimiz tamamen kapalı devre bir altyapı üzerinde çalışmaktadır."
    }
  },
  de: {
    Index: {
      category: "Globale Technologie & KI Intelligenz",
      title1: "Die Zukunft der Technologie",
      title2: "Wird geschrieben, während Sie schlafen.",
      subtitle: "Jenseits der Mainstream-Medien. Entdecken Sie KI-Tools, Durchbrüche von Unternehmen und digitale Innovationen.",
      cta: "Einblicke erkunden",
      ctaLatest: "Neueste Analysen",
      ctaExplore: "Berichte erkunden",
      secFeatured: "Hervorgehoben",
      secLatest: "Neueste Erkenntnisse",
      viewArchive: "Archiv anzeigen",
      readMore: "Weiterlesen",
      statReports: "Berichte",
      statNations: "Länder",
      statSubscribers: "Abonnenten"
    },
    Header: {
      breaking: "EILMELDUNG",
      ticker: [
        "NEUE ÄRA DER KI-REGULIERUNGEN BEGINNT",
        "UNERWARTETER DURCHBRUCH BEI QUANTENCHIPS",
        "GEMEINSAME ERKLÄRUNG VON TECH-GIGANTEN",
        "AUTONOME FAHRZEUGE DER NÄCHSTEN GENERATION",
        "SENTIENT WIRE EXKLUSIV: ARCHITEKTEN DER ZUKUNFT"
      ],
      nav: { home: "STARTSEITE", cybersecurity: "CYBERSICHERHEIT", ai: "KI", hardware: "HARDWARE" },
      login: "Konto-Login"
    },
    Footer: {
      description: "Entdecken Sie die Technologien, Verteidigungsaufträge und Unternehmensstrategien, die die Zukunft prägen.",
      categories: "Kategorien",
      cybersecurity: "Cybersicherheit",
      ai: "KI",
      quantum: "Quanten",
      hardware: "Hardware",
      defense: "Verteidigung",
      corporate: "Unternehmen",
      about: "Über uns",
      careers: "Karriere",
      contact: "Kontakt",
      legal: "Rechtliches",
      privacy: "Datenschutzerklärung",
      terms: "Nutzungsbedingungen",
      cookies: "Cookie-Richtlinie",
      allRightsReserved: "Alle Rechte vorbehalten.",
      systemActive: "SYSTEM AKTIV"
    },
    News: {
      decrypting: "DATENBANK WIRD ENTSCHLÜSSELT...",
      notFound: "404 - GEHEIMDIENST-INFORMATION NICHT GEFUNDEN",
      returnToBase: "ZURÜCK ZUR BASIS",
      decrypted: "ENTSCHLÜSSELT",
      satelliteImagery: "SATELLITENBILDER: GESICHERT",
      terminalTitle: "terminal.exe",
      awaitingTelemetry: "Warten auf weitere Telemetrie",
      shareIntel: "INTEL TEILEN",
      reportId: "BERICHTS-ID",
      t1: "> BEDROHUNGSANALYSE WIRD INITIALISIERT...",
      t2: "> NUTZLASTSIGNATUR [0x9F42C] WIRD ENTSCHLÜSSELT...",
      t3: "[KRITISCH] ZERO-DAY IM SCADA-PROTOKOLL ERKANNT",
      t4: "> BEDROHUNGSURSPRUNG WIRD KARTIERT: UNKNOWN_NODE_492",
      t5: "> SICHERE VERBINDUNG WIRD HERGESTELLT...",
      success: "[ERFOLGREICH]",
      timeout: "[ZEITÜBERSCHREITUNG]",
      escalationTitle: "Die Eskalation der cyber-kinetischen Kriegsführung",
      escalationP1: "Im Gegensatz zu früheren Angriffen, die sich hauptsächlich auf Datenexfiltration und Unternehmensspionage konzentrierten, zeigt dieser jüngste Vektor die klare Absicht, physischen, kinetischen Schaden anzurichten. Durch die Manipulation der Frequenzregler der betroffenen Umspannwerke versuchten die Angreifer, Hardwareausfälle auszulösen, die zu wochenlangen lokalen Stromausfällen hätten führen können.",
      escalationP2: "Globale Geheimdienste arbeiten derzeit mit dem Privatsektor zusammen, um die Schwachstellen zu beheben und den Ursprung des Angriffs zurückzuverfolgen. Bis ein umfassender Patch bereitgestellt wird, bleiben die Netzbetreiber in höchster Alarmbereitschaft. Wir werden die Situation weiter beobachten und über den Live-Ticker Updates bereitstellen."
    }
  },
  es: {
    Index: {
      category: "Tecnología Global e Inteligencia de IA",
      title1: "El Futuro de la Tecnología",
      title2: "Se escribe mientras duermes.",
      subtitle: "Más allá de los principales medios. Descubre las herramientas de IA, avances corporativos e innovaciones.",
      cta: "Explorar artículos",
      ctaLatest: "Últimos análisis",
      ctaExplore: "Explorar informes",
      secFeatured: "Destacado",
      secLatest: "Última información",
      viewArchive: "Ver archivo",
      readMore: "Leer más",
      statReports: "Informes",
      statNations: "Países rastreados",
      statSubscribers: "Suscriptores"
    },
    Header: {
      breaking: "ÚLTIMA HORA",
      ticker: [
        "COMIENZA UNA NUEVA ERA EN REGULACIONES DE IA",
        "AVANCE INESPERADO EN CHIPS CUÁNTICOS",
        "DECLARACIÓN CONJUNTA DE LOS GIGANTES TECNOLÓGICOS",
        "VEHÍCULOS AUTÓNOMOS DE PRUEBA EN LAS CALLES",
        "EXCLUSIVA DE SENTIENT WIRE: ARQUITECTOS DEL FUTURO"
      ],
      nav: { home: "INICIO", cybersecurity: "CIBERSEGURIDAD", ai: "IA", hardware: "HARDWARE" },
      login: "Iniciar sesión"
    },
    Footer: {
      description: "Descubriendo tecnologías, contratos de defensa y estrategias corporativas que definen el futuro.",
      categories: "Categorías",
      cybersecurity: "Ciberseguridad",
      ai: "IA",
      quantum: "Cuántica",
      hardware: "Hardware",
      defense: "Defensa",
      corporate: "Corporación",
      about: "Nosotros",
      careers: "Carreras",
      contact: "Contacto",
      legal: "Legal",
      privacy: "Política de privacidad",
      terms: "Condiciones de servicio",
      cookies: "Política de cookies",
      allRightsReserved: "Todos los derechos reservados.",
      systemActive: "SISTEMA ACTIVO"
    },
    News: {
      decrypting: "DESCIFRANDO BASE DE DATOS...",
      notFound: "404 - INFORMACIÓN NO ENCONTRADA",
      returnToBase: "VOLVER A LA BASE",
      decrypted: "DESCIFRADO",
      satelliteImagery: "IMÁGENES POR SATÉLITE: ASEGURADAS",
      terminalTitle: "terminal.exe",
      awaitingTelemetry: "Esperando más telemetría",
      shareIntel: "COMPARTIR INTELIGENCIA",
      reportId: "ID DE REPORTE",
      t1: "> INICIALIZANDO ANÁLISIS DE AMENAZAS...",
      t2: "> DESCIFRANDO FIRMA DE CARGA ÚTIL [0x9F42C]...",
      t3: "[CRÍTICO] CERO-DAY DETECTADO EN PROTOCOLO SCADA",
      t4: "> MAPEAR ORIGEN DE AMENAZA: UNKNOWN_NODE_492",
      t5: "> ESTABLECIENDO CONEXIÓN SEGURA...",
      success: "[ÉXITO]",
      timeout: "[TIEMPO EXCEDIDO]",
      escalationTitle: "La escalada de la guerra ciber-cinética",
      escalationP1: "A diferencia de ataques anteriores centrados en la filtración de datos y el espionaje corporativo, este último vector demuestra una clara intención de causar daños físicos y cinéticos. Al manipular los controles de frecuencia de las subestaciones objetivo, los atacantes intentaron inducir fallas de hardware que podrían haber resultado en apagones locales de semanas.",
      escalationP2: "Las agencias globales de inteligencia están trabajando junto al sector privado para corregir las vulnerabilidades y rastrear el origen del ataque. Hasta que se implemente un parche completo, los operadores de la red permanecen en alerta máxima. Seguiremos monitoreando la situación y ofreciendo actualizaciones."
    }
  },
  fr: {
    Index: {
      category: "Technologie Mondiale & Intelligence IA",
      title1: "L'Avenir de la Technologie",
      title2: "S'écrit pendant que vous dormez.",
      subtitle: "Au-delà des médias traditionnels. Découvrez les outils d'IA et les innovations qui façonnent demain.",
      cta: "Explorer les Insights",
      ctaLatest: "Dernières analyses",
      ctaExplore: "Explorer les rapports",
      secFeatured: "À la une",
      secLatest: "Dernières analyses",
      viewArchive: "Voir les archives",
      readMore: "Lire la suite",
      statReports: "Rapports",
      statNations: "Pays suivis",
      statSubscribers: "Abonnés"
    },
    Header: {
      breaking: "DERNIÈRE HEURE",
      ticker: [
        "NOUVELLE ÈRE DE RÉGLEMENTATION DE L'IA",
        "PERCÉE INATTENDUE DANS LES PUCES QUANTIQUES",
        "DÉCLARATION CONJOINTE DES GÉANTS DE LA TECH",
        "VÉHICULES AUTONOMES EN TEST DANS LES RUES",
        "EXCLUSIVITÉ SENTIENT WIRE : ARCHITECTES DU FUTUR"
      ],
      nav: { home: "ACCUEIL", cybersecurity: "CYBERSÉCURITÉ", ai: "IA", hardware: "MATÉRIEL" },
      login: "Connexion"
    },
    Footer: {
      description: "Révéler les technologies, les contrats de défense et les stratégies d'entreprise qui façonnent l'avenir.",
      categories: "Catégories",
      cybersecurity: "Cybersécurité",
      ai: "IA",
      quantum: "Quantique",
      hardware: "Matériel",
      defense: "Défense",
      corporate: "Entreprise",
      about: "À propos",
      careers: "Carrières",
      contact: "Contact",
      legal: "Mentions légales",
      privacy: "Politique de confidentialité",
      terms: "Conditions d'utilisation",
      cookies: "Politique de cookies",
      allRightsReserved: "Tous droits réservés.",
      systemActive: "SYSTÈME ACTIF"
    },
    News: {
      decrypting: "DECRYPTAGE DE LA BANQUE DE DONNÉES...",
      notFound: "404 - INFOS NON TROUVÉES",
      returnToBase: "RETOUR À LA BASE",
      decrypted: "DÉCRYPTÉ",
      satelliteImagery: "IMAGERIE SATELLITE : SÉCURISÉE",
      terminalTitle: "terminal.exe",
      awaitingTelemetry: "En attente de télémétrie",
      shareIntel: "PARTAGER LES INFOS",
      reportId: "ID DU RAPPORT",
      t1: "> INITIALISATION DE L'ANALYSE DES MENACES...",
      t2: "> DÉCRYPTAGE DE LA SIGNATURE DE CHARGE UTILE [0x9F42C]...",
      t3: "[CRITIQUE] ZERO-DAY DÉTECTÉ DANS LE PROTOCOLE SCADA",
      t4: "> LOCALISATION DE L'ORIGINE DE LA MENACE : UNKNOWN_NODE_492",
      t5: "> ÉTABLISSEMENT D'UNE CONNEXION SÉCURISÉE...",
      success: "[SUCÈS]",
      timeout: "[EXPIRATION]",
      escalationTitle: "L'escalade de la guerre cyber-cinétique",
      escalationP1: "Contrairement aux attaques précédentes axées sur l'exfiltration de données et l'espionnage d'entreprise, ce dernier vecteur démontre une intention claire de causer des dommages physiques et cinétiques. En manipulant les commandes de fréquence des sous-stations ciblées, les attaquants ont tenté de provoquer des pannes matérielles qui auraient pu entraîner des pannes d'électricité locales de plusieurs semaines.",
      escalationP2: "Les agences de renseignement mondiales travaillent en tandem avec le secteur privé pour corriger les vulnérabilités et retracer l'origine de l'attaque. En attendant le déploiement d'un correctif complet, les gestionnaires de réseau restent en alerte maximale. Nous continuerons à suivre la situation."
    }
  },
  it: {
    Index: {
      category: "Tecnologia Globale & Intelligenza IA",
      title1: "Il Futuro della Tecnologia",
      title2: "Viene scritto mentre dormi.",
      subtitle: "Oltre i media mainstream. Scopri gli strumenti di IA e le innovazioni digitali.",
      cta: "Esplora gli Approfondimenti",
      ctaLatest: "Ultime analisi",
      ctaExplore: "Esplora i rapporti",
      secFeatured: "In evidenza",
      secLatest: "Ultimi aggiornamenti",
      viewArchive: "Visualizza archivio",
      readMore: "Leggi tutto",
      statReports: "Rapporti",
      statNations: "Paesi tracciati",
      statSubscribers: "Iscritti"
    },
    Header: {
      breaking: "ULTIM'ORA",
      ticker: [
        "INIZIA UNA NUOVA ERA NELLE REGOLE SULL'IA",
        "SVOLTA INASPETTATA NEI CHIP QUANTISTICI",
        "DICHIARAZIONE CONGIUNTA DEI GIGANTI DELLA TECH",
        "VEICOLI AUTONOMI TESTATI IN CITTÀ",
        "ESCLUSIVA SENTIENT WIRE: ARCHITETTI DEL FUTURO"
      ],
      nav: { home: "HOME", cybersecurity: "CYBERSECURITY", ai: "IA", hardware: "HARDWARE" },
      login: "Accedi"
    },
    Footer: {
      description: "Svelare le tecnologie, i contratti di difesa e le strategie aziendali che plasmano il futuro.",
      categories: "Categorie",
      cybersecurity: "Cybersecurity",
      ai: "IA",
      quantum: "Quantistica",
      hardware: "Hardware",
      defense: "Difesa",
      corporate: "Società",
      about: "Chi siamo",
      careers: "Carriere",
      contact: "Contatti",
      legal: "Legale",
      privacy: "Informativa sulla privacy",
      terms: "Termini di servizio",
      cookies: "Politica sui cookie",
      allRightsReserved: "Tutti i diritti riservati.",
      systemActive: "SISTEMA ATTIVO"
    },
    News: {
      decrypting: "DECRIPTAZIONE BANCA DATI...",
      notFound: "404 - INFORMAZIONE NON TROVATA",
      returnToBase: "TORNA ALLA BASE",
      decrypted: "DECRIPTATO",
      satelliteImagery: "IMMAGINI SATELLITARI: SICURE",
      terminalTitle: "terminal.exe",
      awaitingTelemetry: "In attesa di ulteriore telemetria",
      shareIntel: "CONDIVIDI INFORMAZIONE",
      reportId: "ID RAPPORTO",
      t1: "> INIZIALIZZAZIONE ANALISI DELLE MINACCE...",
      t2: "> DECRIPTAZIONE FIRMA DEL CARICO [0x9F42C]...",
      t3: "[CRITICO] ZERO-DAY RILEVATO NEL PROTOCOLLO SCADA",
      t4: "> MAPPATURA ORIGINE DELLA MINACCIA: UNKNOWN_NODE_492",
      t5: "> CONFIGURAZIONE CONNESSIONE SICURA...",
      success: "[SUCCESSO]",
      timeout: "[TEMPO SCADUTO]",
      escalationTitle: "L'escalation della guerra ciber-cinetica",
      escalationP1: "A differenza degli attacchi precedenti focalizzati principalmente sull'esfiltrazione di dati e sullo spionaggio industriale, questo ultimo vettore mostra un chiaro intento di causare danni fisici e cinetici. Manipolando i controlli di frequenza delle sottostazioni prese di mira, gli aggressori hanno cercato di indurre guasti hardware che avrebbero potuto causare blackout locali di settimane.",
      escalationP2: "Le agenzie di intelligence globali stanno lavorando insieme al settore privato per correggere le vulnerabilità e tracciare l'origine dell'attacco. Fino all'implementazione di una patch completa, gli operatori di rete rimangono in allerta. Monitoreremo la situazione per fornire aggiornamenti."
    }
  },
  nl: {
    Index: {
      category: "Wereldwijde Technologie & AI",
      title1: "De Toekomst van Technologie",
      title2: "Wordt geschreven terwijl u slaapt.",
      subtitle: "Voorbij de reguliere media. Ontdek de AI-tools en innovaties van de toekomst.",
      cta: "Ontdek Inzichten",
      ctaLatest: "Nieuwste analyse",
      ctaExplore: "Ontdek rapporten",
      secFeatured: "Uitgelicht",
      secLatest: "Laatste updates",
      viewArchive: "Bekijk archief",
      readMore: "Lees meer",
      statReports: "Rapporten",
      statNations: "Landen gevolgd",
      statSubscribers: "Abonnees"
    },
    Header: {
      breaking: "LAATSTE NIEUWS",
      ticker: [
        "NIEUW TIJDPERK IN AI-REGELGEVING BEGINT",
        "ONVERWACHTE DOORBRAAK IN QUANTUM CHIPS",
        "GEZAMENLIJKE VERKLARING VAN TECHREUZEN",
        "AUTONOME VOERTUIGEN OP STRAAT GETEST",
        "SENTIENT WIRE EXCLUSIEF: ARCHITECTEN VAN DE TOEKOMST"
      ],
      nav: { home: "HOME", cybersecurity: "CYBERSECURITY", ai: "AI", hardware: "HARDWARE" },
      login: "Inloggen"
    },
    Footer: {
      description: "Ontdek de technologieën, defensiecontracten en bedrijfsstrategieën die de toekomst bepalen.",
      categories: "Categorieën",
      cybersecurity: "Cybersecurity",
      ai: "AI",
      quantum: "Quantum",
      hardware: "Hardware",
      defense: "Defensie",
      corporate: "Zakelijk",
      about: "Over ons",
      careers: "Vacatures",
      contact: "Contact",
      legal: "Juridisch",
      privacy: "Privacybeleid",
      terms: "Gebruiksvoorwaarden",
      cookies: "Cookiebeleid",
      allRightsReserved: "Alle rechten voorbehouden.",
      systemActive: "SYSTEEM ACTIEF"
    },
    News: {
      decrypting: "DATABASE DECRYPTEREN...",
      notFound: "404 - INTEL NIET GEVONDEN",
      returnToBase: "TERUG NAAR BASIS",
      decrypted: "GECRYPTEERD",
      satelliteImagery: "SATELLIETBEELDEN: BEVEILIGD",
      terminalTitle: "terminal.exe",
      awaitingTelemetry: "Wachtend op verdere telemetrie",
      shareIntel: "DEEL INTEL",
      reportId: "RAPOR KODU",
      t1: "> INITIALISEREN DREIGINGSANALYSE...",
      t2: "> PAYLOAD-HANDTEKENING DECRYPTEREN [0x9F42C]...",
      t3: "[KRITIEK] ZERO-DAY GEDETECTEERD IN SCADA-PROTOCOL",
      t4: "> DREIGINGSBRON IN KAART BRENGEN: UNKNOWN_NODE_492",
      t5: "> BEVEILIGDE HANDSHAKE TOT STAND BRENGEN...",
      success: "[SUCCES]",
      timeout: "[TIMEOUT]",
      escalationTitle: "De escalatie van cyber-kinetische oorlogsvoering",
      escalationP1: "In tegenstelling tot eerdere aanvallen die primair gericht waren op data-exfiltratie en bedrijfsspionage, toont deze nieuwste vector een duidelijke intentie om fysieke, kinetische schade aan te richten. Door de frequentieregelaars van de doelstations te manipuleren, probeerden de aanvallers hardwarestoringen te veroorzaken die hadden kunnen leiden tot wekenlange lokale stroomuitval.",
      escalationP2: "Wereldwijde inlichtingendiensten werken momenteel samen met de particuliere sector om de kwetsbaarheden te verhelpen en de herkomst van de aanval te traceren. Totdat er een volledige patch is geïmplementeerd, blijven netbeheerders in hoge staat van paraatheid. We blijven de situatie volgen."
    }
  },
  pl: {
    Index: {
      category: "Globalna Technologia i Sztuczna Inteligencja",
      title1: "Przyszłość Technologii",
      title2: "Pisze się, gdy śpisz.",
      subtitle: "Poza głównym nurtem. Odkryj narzędzia AI i cyfrowe innowacje kształtujące jutro.",
      cta: "Odkryj więcej",
      ctaLatest: "Najnowsze analizy",
      ctaExplore: "Przeglądaj raporty",
      secFeatured: "Polecane",
      secLatest: "Najnowsze informacje",
      viewArchive: "Zobacz archiwum",
      readMore: "Więcej",
      statReports: "Raporty",
      statNations: "Śledzone kraje",
      statSubscribers: "Subskrybenci"
    },
    Header: {
      breaking: "Z OSTATNIEJ CHWILI",
      ticker: [
        "POCZĄTEK NOWEJ ERY REGULACJI AI",
        "NIESPODZIEWANY PRZEŁOM W CHIPACH KWANTOWYCH",
        "WSPÓLNE OŚWIADCZENIE GIGANTÓW TECHNOLOGICZNYCH",
        "TESTY AUTONOMICZNYCH POJAZDÓW W MIASTACH",
        "TYLKO U NAS: ARCHITEKCI PRZYSZŁOŚCI"
      ],
      nav: { home: "GŁÓWNA", cybersecurity: "CYBERBEZPIECZEŃSTWO", ai: "AI", hardware: "SPRZĘT" },
      login: "Zaloguj"
    },
    Footer: {
      description: "Odkrywaj technologie, kontrakty obronne i strategie korporacyjne, które kształtują przyszłość.",
      categories: "Kategorie",
      cybersecurity: "Cyberbezpieczeństwo",
      ai: "AI",
      quantum: "Kwanty",
      hardware: "Sprzęt",
      defense: "Obronność",
      corporate: "Firma",
      about: "O nas",
      careers: "Kariera",
      contact: "Kontakt",
      legal: "Prawo",
      privacy: "Polityka prywatności",
      terms: "Regulamin świadczenia usług",
      cookies: "Polityka cookies",
      allRightsReserved: "Wszelkie prawa zastrzeżone.",
      systemActive: "SYSTEM AKTYWNY"
    },
    News: {
      decrypting: "DESZYFROWANIE BAZY DANYCH...",
      notFound: "404 - NIE ZNALEZIONO DANYCH",
      returnToBase: "POWRÓT DO BAZY",
      decrypted: "ODSZYFROWANO",
      satelliteImagery: "ZDJĘCIA SATELITARNE: ZABEZPIECZONE",
      terminalTitle: "terminal.exe",
      awaitingTelemetry: "Oczekiwanie na dalszą telemetrię",
      shareIntel: "UDOSTĘPNIJ DANE",
      reportId: "ID RAPORTU",
      t1: "> INICJOWANIE ANALIZY ZAGROŻEŃ...",
      t2: "> ODSZYFROWYWANIE SYGNATURY ŁADUNKU [0x9F42C]...",
      t3: "[KRYTYCZNY] WYKRYTO BŁĄD ZERO-DAY W PROTOKOLE SCADA",
      t4: "> MAPOWANIE ŹRÓDŁA ZAGROŻENIA: UNKNOWN_NODE_492",
      t5: "> NAWIĄZYWANIE BEZPIECZNEGO POŁĄCZENIA...",
      success: "[SUKCES]",
      timeout: "[LIMIT CZASU]",
      escalationTitle: "Eskalacja cyber-kinetycznej wojny",
      escalationP1: "W przeciwieństwie do wcześniejszych ataków skupiających się głównie na wykradaniu danych i szpiegostwie korporacyjnym, ten ostatni wektor wykazuje wyraźny zamiar wywołania szkód fizycznych i kinetycznych. Manipulując sterowaniem częstotliwością stacji transformatorowych, napastnicy próbowali wywołać awarie sprzętu, co mogło spowodować lokalne przerwy w dostawie prądu trwające tygodnie.",
      escalationP2: "Globalne agencje wywiadowcze współpracują z sektorem prywatnym w celu załatania luk i wyśledzenia źródła ataku. Do czasu wdrożenia pełnej łatki operatorzy sieci pozostają w stanie podwyższonej gotowości. Będziemy nadal monitorować sytuację."
    }
  }
};

// Aliases for EN variants
languages['en-US'] = languages.en;
languages['en-GB'] = languages.en;
languages['en-CA'] = languages.en;

for (const [lang, data] of Object.entries(languages)) {
  fs.writeFileSync('./messages/' + lang + '.json', JSON.stringify(data, null, 2));
}
console.log('Translations generated successfully!');
